# Generated by Django 3.0.5 on 2020-04-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(help_text='할 일을 채워주세요!', max_length=200)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
